// pkg/plugin-sdk/proto/plugin.proto
// 插件通信契约（M3.3）：主进程（internal/plugin）与插件子进程（pkg/plugin-sdk/server）共用。
// 对齐 docs/architecture.md 6.2 三服务设计：
//   - PluginService：生命周期（Info/Activate/Deactivate）
//   - HookService：同步钩子执行（Execute；流式 Stream 后置）
//   - PluginAPI：插件自定义 API（主进程按 /api/plugins/{id}/** 代理）
//
// 生成方式：./scripts/gen-proto.sh（buf + protoc-gen-go/protoc-gen-go-grpc）
// 生成的 .pb.go 提交仓库，第三方插件作者无需安装工具链。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty 空请求（无参数 RPC）。
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

// PluginInfo 插件信息（Info 返回，主进程校验插件声明与清单一致）。
type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                   // 插件 ID（唯一，与清单 id 一致）
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // 插件名称
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`         // 版本号
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`           // 作者
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"` // 一句话描述
	Hooks         []string               `protobuf:"bytes,6,rep,name=hooks,proto3" json:"hooks,omitempty"`             // 声明的钩子（对齐主进程钩子表，如 "post.after_publish"）
	Apis          []string               `protobuf:"bytes,7,rep,name=apis,proto3" json:"apis,omitempty"`               // 自定义 API 路径（如 "/ping"，主进程挂 /api/plugins/{id}/**）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetHooks() []string {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *PluginInfo) GetApis() []string {
	if x != nil {
		return x.Apis
	}
	return nil
}

// Status 激活/停用结果。
type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`      // 是否成功
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // 错误信息（ok=false 时）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *Status) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Status) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// HookRequest 钩子执行请求（主进程 → 插件；payload 为 JSON bytes）。
type HookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hook          string                 `protobuf:"bytes,1,opt,name=hook,proto3" json:"hook,omitempty"`                       // 钩子名（对齐主进程钩子常量）
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`  // 请求追踪 ID（贯穿日志）
	ActorId       int64                  `protobuf:"varint,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"` // 操作者用户 ID（0=匿名/系统）
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                 // 载荷 JSON（各钩子自定义结构，主进程传值副本）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookRequest) Reset() {
	*x = HookRequest{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookRequest) ProtoMessage() {}

func (x *HookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookRequest.ProtoReflect.Descriptor instead.
func (*HookRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *HookRequest) GetHook() string {
	if x != nil {
		return x.Hook
	}
	return ""
}

func (x *HookRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *HookRequest) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *HookRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// HookResponse 钩子执行响应。
//   - ok=false：同步拦截钩子拒绝（reason 为用户可读原因，阻断核心流程）
//   - modify：可改写钩子（search.query）返回改写后的载荷 JSON
type HookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`        // 是否放行（false=拒绝）
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // 拒绝原因（用户可读）
	Modify        []byte                 `protobuf:"bytes,3,opt,name=modify,proto3" json:"modify,omitempty"` // 改写结果 JSON（可空）
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`   // 插件内部错误（主进程记录 last_error，不阻断核心）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookResponse) Reset() {
	*x = HookResponse{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookResponse) ProtoMessage() {}

func (x *HookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookResponse.ProtoReflect.Descriptor instead.
func (*HookResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *HookResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HookResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *HookResponse) GetModify() []byte {
	if x != nil {
		return x.Modify
	}
	return nil
}

func (x *HookResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// APICall 插件自定义 API 调用（主进程代理转发）。
type APICall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"` // HTTP 方法（GET/POST/PUT/DELETE...）
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`     // 路径（如 "/ping"）
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`     // 请求体 JSON（可空）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APICall) Reset() {
	*x = APICall{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APICall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APICall) ProtoMessage() {}

func (x *APICall) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APICall.ProtoReflect.Descriptor instead.
func (*APICall) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *APICall) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *APICall) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *APICall) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// APICallResult 插件 API 响应。
type APICallResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // HTTP 状态码（200 正常）
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`      // 响应体 JSON
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`    // 插件内部错误（非 HTTP 错误）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APICallResult) Reset() {
	*x = APICallResult{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APICallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APICallResult) ProtoMessage() {}

func (x *APICallResult) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APICallResult.ProtoReflect.Descriptor instead.
func (*APICallResult) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *APICallResult) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *APICallResult) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *APICallResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// LicenseInfo 许可证信息（M3.5：主进程激活时下发，插件只读；主进程是唯一数据源）。
type LicenseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edition       string                 `protobuf:"bytes,1,opt,name=edition,proto3" json:"edition,omitempty"`                       // 版本：free（demo）/ pro（已激活）
	Features      []string               `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"`                     // 授权功能列表（FeatureEnabled 判断依据）
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // 到期时间戳（Unix 秒；0=永久）
	Degraded      bool                   `protobuf:"varint,4,opt,name=degraded,proto3" json:"degraded,omitempty"`                    // 已降级（超宽限期未续费，功能锁定）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LicenseInfo) Reset() {
	*x = LicenseInfo{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LicenseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LicenseInfo) ProtoMessage() {}

func (x *LicenseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LicenseInfo.ProtoReflect.Descriptor instead.
func (*LicenseInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *LicenseInfo) GetEdition() string {
	if x != nil {
		return x.Edition
	}
	return ""
}

func (x *LicenseInfo) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *LicenseInfo) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *LicenseInfo) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x10yueyan.plugin.v1\"\a\n" +
	"\x05Empty\"\xae\x01\n" +
	"\n" +
	"PluginInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05hooks\x18\x06 \x03(\tR\x05hooks\x12\x12\n" +
	"\x04apis\x18\a \x03(\tR\x04apis\".\n" +
	"\x06Status\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"q\n" +
	"\vHookRequest\x12\x12\n" +
	"\x04hook\x18\x01 \x01(\tR\x04hook\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\x03R\aactorId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"d\n" +
	"\fHookResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x16\n" +
	"\x06modify\x18\x03 \x01(\fR\x06modify\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"I\n" +
	"\aAPICall\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"Q\n" +
	"\rAPICallResult\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"~\n" +
	"\vLicenseInfo\x12\x18\n" +
	"\aedition\x18\x01 \x01(\tR\aedition\x12\x1a\n" +
	"\bfeatures\x18\x02 \x03(\tR\bfeatures\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x1a\n" +
	"\bdegraded\x18\x04 \x01(\bR\bdegraded2\xd4\x01\n" +
	"\rPluginService\x12=\n" +
	"\x04Info\x12\x17.yueyan.plugin.v1.Empty\x1a\x1c.yueyan.plugin.v1.PluginInfo\x12C\n" +
	"\bActivate\x12\x1d.yueyan.plugin.v1.LicenseInfo\x1a\x18.yueyan.plugin.v1.Status\x12?\n" +
	"\n" +
	"Deactivate\x12\x17.yueyan.plugin.v1.Empty\x1a\x18.yueyan.plugin.v1.Status2W\n" +
	"\vHookService\x12H\n" +
	"\aExecute\x12\x1d.yueyan.plugin.v1.HookRequest\x1a\x1e.yueyan.plugin.v1.HookResponse2O\n" +
	"\tPluginAPI\x12B\n" +
	"\x04Call\x12\x19.yueyan.plugin.v1.APICall\x1a\x1f.yueyan.plugin.v1.APICallResultB5Z3github.com/roberts9012062/boke/pkg/plugin-sdk/protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_plugin_proto_goTypes = []any{
	(*Empty)(nil),         // 0: yueyan.plugin.v1.Empty
	(*PluginInfo)(nil),    // 1: yueyan.plugin.v1.PluginInfo
	(*Status)(nil),        // 2: yueyan.plugin.v1.Status
	(*HookRequest)(nil),   // 3: yueyan.plugin.v1.HookRequest
	(*HookResponse)(nil),  // 4: yueyan.plugin.v1.HookResponse
	(*APICall)(nil),       // 5: yueyan.plugin.v1.APICall
	(*APICallResult)(nil), // 6: yueyan.plugin.v1.APICallResult
	(*LicenseInfo)(nil),   // 7: yueyan.plugin.v1.LicenseInfo
}
var file_plugin_proto_depIdxs = []int32{
	0, // 0: yueyan.plugin.v1.PluginService.Info:input_type -> yueyan.plugin.v1.Empty
	7, // 1: yueyan.plugin.v1.PluginService.Activate:input_type -> yueyan.plugin.v1.LicenseInfo
	0, // 2: yueyan.plugin.v1.PluginService.Deactivate:input_type -> yueyan.plugin.v1.Empty
	3, // 3: yueyan.plugin.v1.HookService.Execute:input_type -> yueyan.plugin.v1.HookRequest
	5, // 4: yueyan.plugin.v1.PluginAPI.Call:input_type -> yueyan.plugin.v1.APICall
	1, // 5: yueyan.plugin.v1.PluginService.Info:output_type -> yueyan.plugin.v1.PluginInfo
	2, // 6: yueyan.plugin.v1.PluginService.Activate:output_type -> yueyan.plugin.v1.Status
	2, // 7: yueyan.plugin.v1.PluginService.Deactivate:output_type -> yueyan.plugin.v1.Status
	4, // 8: yueyan.plugin.v1.HookService.Execute:output_type -> yueyan.plugin.v1.HookResponse
	6, // 9: yueyan.plugin.v1.PluginAPI.Call:output_type -> yueyan.plugin.v1.APICallResult
	5, // [5:10] is the sub-list for method output_type
	0, // [0:5] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
