// pkg/plugin-sdk/proto/plugin.proto
// 插件通信契约（M3.3）：主进程（internal/plugin）与插件子进程（pkg/plugin-sdk/server）共用。
// 对齐 docs/architecture.md 6.2 三服务设计：
//   - PluginService：生命周期（Info/Activate/Deactivate）
//   - HookService：同步钩子执行（Execute；流式 Stream 后置）
//   - PluginAPI：插件自定义 API（主进程按 /api/plugins/{id}/** 代理）
//
// 生成方式：./scripts/gen-proto.sh（buf + protoc-gen-go/protoc-gen-go-grpc）
// 生成的 .pb.go 提交仓库，第三方插件作者无需安装工具链。

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PluginService_Info_FullMethodName       = "/yueyan.plugin.v1.PluginService/Info"
	PluginService_Activate_FullMethodName   = "/yueyan.plugin.v1.PluginService/Activate"
	PluginService_Deactivate_FullMethodName = "/yueyan.plugin.v1.PluginService/Deactivate"
)

// PluginServiceClient is the client API for PluginService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginService 插件生命周期服务。
type PluginServiceClient interface {
	// Info 返回插件信息（启用时校验声明与安装清单一致）。
	Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error)
	// Activate 激活（携带主进程下发的许可证信息；插件侧更新内存并初始化资源）。
	Activate(ctx context.Context, in *LicenseInfo, opts ...grpc.CallOption) (*Status, error)
	// Deactivate 停用（停用回调，插件侧保存状态/释放资源）。
	Deactivate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error)
}

type pluginServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginServiceClient(cc grpc.ClientConnInterface) PluginServiceClient {
	return &pluginServiceClient{cc}
}

func (c *pluginServiceClient) Info(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*PluginInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PluginInfo)
	err := c.cc.Invoke(ctx, PluginService_Info_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Activate(ctx context.Context, in *LicenseInfo, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, PluginService_Activate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pluginServiceClient) Deactivate(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Status, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Status)
	err := c.cc.Invoke(ctx, PluginService_Deactivate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginServiceServer is the server API for PluginService service.
// All implementations must embed UnimplementedPluginServiceServer
// for forward compatibility.
//
// PluginService 插件生命周期服务。
type PluginServiceServer interface {
	// Info 返回插件信息（启用时校验声明与安装清单一致）。
	Info(context.Context, *Empty) (*PluginInfo, error)
	// Activate 激活（携带主进程下发的许可证信息；插件侧更新内存并初始化资源）。
	Activate(context.Context, *LicenseInfo) (*Status, error)
	// Deactivate 停用（停用回调，插件侧保存状态/释放资源）。
	Deactivate(context.Context, *Empty) (*Status, error)
	mustEmbedUnimplementedPluginServiceServer()
}

// UnimplementedPluginServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginServiceServer struct{}

func (UnimplementedPluginServiceServer) Info(context.Context, *Empty) (*PluginInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method Info not implemented")
}
func (UnimplementedPluginServiceServer) Activate(context.Context, *LicenseInfo) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method Activate not implemented")
}
func (UnimplementedPluginServiceServer) Deactivate(context.Context, *Empty) (*Status, error) {
	return nil, status.Error(codes.Unimplemented, "method Deactivate not implemented")
}
func (UnimplementedPluginServiceServer) mustEmbedUnimplementedPluginServiceServer() {}
func (UnimplementedPluginServiceServer) testEmbeddedByValue()                       {}

// UnsafePluginServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginServiceServer will
// result in compilation errors.
type UnsafePluginServiceServer interface {
	mustEmbedUnimplementedPluginServiceServer()
}

func RegisterPluginServiceServer(s grpc.ServiceRegistrar, srv PluginServiceServer) {
	// If the following call panics, it indicates UnimplementedPluginServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginService_ServiceDesc, srv)
}

func _PluginService_Info_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Info(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Info_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Info(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Activate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LicenseInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Activate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Activate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Activate(ctx, req.(*LicenseInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _PluginService_Deactivate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginServiceServer).Deactivate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginService_Deactivate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginServiceServer).Deactivate(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginService_ServiceDesc is the grpc.ServiceDesc for PluginService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yueyan.plugin.v1.PluginService",
	HandlerType: (*PluginServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Info",
			Handler:    _PluginService_Info_Handler,
		},
		{
			MethodName: "Activate",
			Handler:    _PluginService_Activate_Handler,
		},
		{
			MethodName: "Deactivate",
			Handler:    _PluginService_Deactivate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	HookService_Execute_FullMethodName = "/yueyan.plugin.v1.HookService/Execute"
)

// HookServiceClient is the client API for HookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HookService 钩子执行服务。
type HookServiceClient interface {
	// Execute 同步钩子执行（可拦截/改写；异步钩子由主进程后台调用）。
	Execute(ctx context.Context, in *HookRequest, opts ...grpc.CallOption) (*HookResponse, error)
}

type hookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHookServiceClient(cc grpc.ClientConnInterface) HookServiceClient {
	return &hookServiceClient{cc}
}

func (c *hookServiceClient) Execute(ctx context.Context, in *HookRequest, opts ...grpc.CallOption) (*HookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HookResponse)
	err := c.cc.Invoke(ctx, HookService_Execute_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HookServiceServer is the server API for HookService service.
// All implementations must embed UnimplementedHookServiceServer
// for forward compatibility.
//
// HookService 钩子执行服务。
type HookServiceServer interface {
	// Execute 同步钩子执行（可拦截/改写；异步钩子由主进程后台调用）。
	Execute(context.Context, *HookRequest) (*HookResponse, error)
	mustEmbedUnimplementedHookServiceServer()
}

// UnimplementedHookServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHookServiceServer struct{}

func (UnimplementedHookServiceServer) Execute(context.Context, *HookRequest) (*HookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedHookServiceServer) mustEmbedUnimplementedHookServiceServer() {}
func (UnimplementedHookServiceServer) testEmbeddedByValue()                     {}

// UnsafeHookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HookServiceServer will
// result in compilation errors.
type UnsafeHookServiceServer interface {
	mustEmbedUnimplementedHookServiceServer()
}

func RegisterHookServiceServer(s grpc.ServiceRegistrar, srv HookServiceServer) {
	// If the following call panics, it indicates UnimplementedHookServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HookService_ServiceDesc, srv)
}

func _HookService_Execute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HookServiceServer).Execute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HookService_Execute_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HookServiceServer).Execute(ctx, req.(*HookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HookService_ServiceDesc is the grpc.ServiceDesc for HookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yueyan.plugin.v1.HookService",
	HandlerType: (*HookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Execute",
			Handler:    _HookService_Execute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

const (
	PluginAPI_Call_FullMethodName = "/yueyan.plugin.v1.PluginAPI/Call"
)

// PluginAPIClient is the client API for PluginAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PluginAPI 插件自定义 API 服务（主进程按前缀路由代理）。
type PluginAPIClient interface {
	// Call 分发插件自定义 API 调用。
	Call(ctx context.Context, in *APICall, opts ...grpc.CallOption) (*APICallResult, error)
}

type pluginAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewPluginAPIClient(cc grpc.ClientConnInterface) PluginAPIClient {
	return &pluginAPIClient{cc}
}

func (c *pluginAPIClient) Call(ctx context.Context, in *APICall, opts ...grpc.CallOption) (*APICallResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(APICallResult)
	err := c.cc.Invoke(ctx, PluginAPI_Call_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PluginAPIServer is the server API for PluginAPI service.
// All implementations must embed UnimplementedPluginAPIServer
// for forward compatibility.
//
// PluginAPI 插件自定义 API 服务（主进程按前缀路由代理）。
type PluginAPIServer interface {
	// Call 分发插件自定义 API 调用。
	Call(context.Context, *APICall) (*APICallResult, error)
	mustEmbedUnimplementedPluginAPIServer()
}

// UnimplementedPluginAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPluginAPIServer struct{}

func (UnimplementedPluginAPIServer) Call(context.Context, *APICall) (*APICallResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Call not implemented")
}
func (UnimplementedPluginAPIServer) mustEmbedUnimplementedPluginAPIServer() {}
func (UnimplementedPluginAPIServer) testEmbeddedByValue()                   {}

// UnsafePluginAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PluginAPIServer will
// result in compilation errors.
type UnsafePluginAPIServer interface {
	mustEmbedUnimplementedPluginAPIServer()
}

func RegisterPluginAPIServer(s grpc.ServiceRegistrar, srv PluginAPIServer) {
	// If the following call panics, it indicates UnimplementedPluginAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PluginAPI_ServiceDesc, srv)
}

func _PluginAPI_Call_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APICall)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PluginAPIServer).Call(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PluginAPI_Call_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PluginAPIServer).Call(ctx, req.(*APICall))
	}
	return interceptor(ctx, in, info, handler)
}

// PluginAPI_ServiceDesc is the grpc.ServiceDesc for PluginAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PluginAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "yueyan.plugin.v1.PluginAPI",
	HandlerType: (*PluginAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Call",
			Handler:    _PluginAPI_Call_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
