// pkg/plugin-sdk/proto/plugin.proto
// 插件通信契约（M3.3）：主进程（internal/plugin）与插件子进程（pkg/plugin-sdk/server）共用。
// 对齐 docs/architecture.md 6.2 三服务设计：
//   - PluginService：生命周期（Info/Activate/Deactivate）
//   - HookService：同步钩子执行（Execute；流式 Stream 后置）
//   - PluginAPI：插件自定义 API（主进程按 /api/plugins/{id}/** 代理）
//
// 生成方式：./scripts/gen-proto.sh（buf + protoc-gen-go/protoc-gen-go-grpc）
// 生成的 .pb.go 提交仓库，第三方插件作者无需安装工具链。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Empty 空请求（无参数 RPC）。
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{0}
}

// PluginInfo 插件信息（Info 返回，主进程校验插件声明与清单一致）。
type PluginInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                     // 插件 ID（唯一，与清单 id 一致）
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                 // 插件名称
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`           // 版本号
	Author        string                 `protobuf:"bytes,4,opt,name=author,proto3" json:"author,omitempty"`             // 作者
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`   // 一句话描述
	Hooks         []string               `protobuf:"bytes,6,rep,name=hooks,proto3" json:"hooks,omitempty"`               // 声明的钩子（对齐主进程钩子表，如 "post.after_publish"）
	Apis          []string               `protobuf:"bytes,7,rep,name=apis,proto3" json:"apis,omitempty"`                 // 自定义 API 路径（如 "/ping"，主进程挂 /api/plugins/{id}/**）
	Settings      []*SettingField        `protobuf:"bytes,8,rep,name=settings,proto3" json:"settings,omitempty"`         // 设置项声明（设置页 schema 驱动；主进程聚合「进程上报优先、市场清单兜底」）
	Capabilities  []string               `protobuf:"bytes,9,rep,name=capabilities,proto3" json:"capabilities,omitempty"` // 能力声明（授权模型：hooks/api/frontend/settings 基础 + data.read 扩展）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInfo.ProtoReflect.Descriptor instead.
func (*PluginInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *PluginInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PluginInfo) GetHooks() []string {
	if x != nil {
		return x.Hooks
	}
	return nil
}

func (x *PluginInfo) GetApis() []string {
	if x != nil {
		return x.Apis
	}
	return nil
}

func (x *PluginInfo) GetSettings() []*SettingField {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *PluginInfo) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// SettingField 插件设置项声明（设置页 schema 驱动通用渲染器）。
type SettingField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`         // 设置键（存 plugin_instances.config：config["{key}"]）
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`     // 展示标签
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`       // 控件类型：text / switch / select
	Default       string                 `protobuf:"bytes,4,opt,name=default,proto3" json:"default,omitempty"` // 默认值
	Options       []string               `protobuf:"bytes,5,rep,name=options,proto3" json:"options,omitempty"` // select 选项列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingField) Reset() {
	*x = SettingField{}
	mi := &file_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingField) ProtoMessage() {}

func (x *SettingField) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingField.ProtoReflect.Descriptor instead.
func (*SettingField) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *SettingField) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SettingField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *SettingField) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SettingField) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *SettingField) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

// ConfigInfo 插件配置（主进程 → 插件：启动激活时下发 + 保存配置时推送）。
type ConfigInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 配置键值对（仅 schema 声明的 key）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigInfo) Reset() {
	*x = ConfigInfo{}
	mi := &file_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigInfo) ProtoMessage() {}

func (x *ConfigInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigInfo.ProtoReflect.Descriptor instead.
func (*ConfigInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ConfigInfo) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

// Status 激活/停用结果。
type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`      // 是否成功
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"` // 错误信息（ok=false 时）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *Status) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Status) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// HookRequest 钩子执行请求（主进程 → 插件；payload 为 JSON bytes）。
type HookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hook          string                 `protobuf:"bytes,1,opt,name=hook,proto3" json:"hook,omitempty"`                       // 钩子名（对齐主进程钩子常量）
	TraceId       string                 `protobuf:"bytes,2,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`  // 请求追踪 ID（贯穿日志）
	ActorId       int64                  `protobuf:"varint,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"` // 操作者用户 ID（0=匿名/系统）
	Payload       []byte                 `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`                 // 载荷 JSON（各钩子自定义结构，主进程传值副本）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookRequest) Reset() {
	*x = HookRequest{}
	mi := &file_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookRequest) ProtoMessage() {}

func (x *HookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookRequest.ProtoReflect.Descriptor instead.
func (*HookRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *HookRequest) GetHook() string {
	if x != nil {
		return x.Hook
	}
	return ""
}

func (x *HookRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *HookRequest) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *HookRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// HookResponse 钩子执行响应。
//   - ok=false：同步拦截钩子拒绝（reason 为用户可读原因，阻断核心流程）
//   - modify：可改写钩子（search.query）返回改写后的载荷 JSON
type HookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`        // 是否放行（false=拒绝）
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"` // 拒绝原因（用户可读）
	Modify        []byte                 `protobuf:"bytes,3,opt,name=modify,proto3" json:"modify,omitempty"` // 改写结果 JSON（可空）
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`   // 插件内部错误（主进程记录 last_error，不阻断核心）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookResponse) Reset() {
	*x = HookResponse{}
	mi := &file_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookResponse) ProtoMessage() {}

func (x *HookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookResponse.ProtoReflect.Descriptor instead.
func (*HookResponse) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *HookResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *HookResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *HookResponse) GetModify() []byte {
	if x != nil {
		return x.Modify
	}
	return nil
}

func (x *HookResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// APICall 插件自定义 API 调用（主进程代理转发）。
type APICall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"` // HTTP 方法（GET/POST/PUT/DELETE...）
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`     // 路径（如 "/ping"）
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`     // 请求体 JSON（可空）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APICall) Reset() {
	*x = APICall{}
	mi := &file_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APICall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APICall) ProtoMessage() {}

func (x *APICall) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APICall.ProtoReflect.Descriptor instead.
func (*APICall) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *APICall) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *APICall) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *APICall) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

// APICallResult 插件 API 响应。
type APICallResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"` // HTTP 状态码（200 正常）
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`      // 响应体 JSON
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`    // 插件内部错误（非 HTTP 错误）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *APICallResult) Reset() {
	*x = APICallResult{}
	mi := &file_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *APICallResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APICallResult) ProtoMessage() {}

func (x *APICallResult) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APICallResult.ProtoReflect.Descriptor instead.
func (*APICallResult) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *APICallResult) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *APICallResult) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *APICallResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// LicenseInfo 许可证信息（M3.5：主进程激活时下发，插件只读；主进程是唯一数据源）。
type LicenseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edition       string                 `protobuf:"bytes,1,opt,name=edition,proto3" json:"edition,omitempty"`                       // 版本：free（demo）/ pro（已激活）
	Features      []string               `protobuf:"bytes,2,rep,name=features,proto3" json:"features,omitempty"`                     // 授权功能列表（FeatureEnabled 判断依据）
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // 到期时间戳（Unix 秒；0=永久）
	Degraded      bool                   `protobuf:"varint,4,opt,name=degraded,proto3" json:"degraded,omitempty"`                    // 已降级（超宽限期未续费，功能锁定）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LicenseInfo) Reset() {
	*x = LicenseInfo{}
	mi := &file_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LicenseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LicenseInfo) ProtoMessage() {}

func (x *LicenseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LicenseInfo.ProtoReflect.Descriptor instead.
func (*LicenseInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *LicenseInfo) GetEdition() string {
	if x != nil {
		return x.Edition
	}
	return ""
}

func (x *LicenseInfo) GetFeatures() []string {
	if x != nil {
		return x.Features
	}
	return nil
}

func (x *LicenseInfo) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *LicenseInfo) GetDegraded() bool {
	if x != nil {
		return x.Degraded
	}
	return false
}

// UserRequest 用户查询请求。
type UserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 用户 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserRequest) Reset() {
	*x = UserRequest{}
	mi := &file_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserRequest) ProtoMessage() {}

func (x *UserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserRequest.ProtoReflect.Descriptor instead.
func (*UserRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *UserRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

// UserInfo 用户信息（脱敏：不含邮箱/手机/密码等敏感字段）。
type UserInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                               // 用户 ID
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`                    // 昵称
	AvatarUrl     string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"` // 头像 URL
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`                            // 角色（superadmin/admin/author/visitor）
	Bio           string                 `protobuf:"bytes,5,opt,name=bio,proto3" json:"bio,omitempty"`                              // 个人简介
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *UserInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UserInfo) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *UserInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *UserInfo) GetBio() string {
	if x != nil {
		return x.Bio
	}
	return ""
}

// PostRequest 帖子查询请求。
type PostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PostId        int64                  `protobuf:"varint,1,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"` // 帖子 ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostRequest) Reset() {
	*x = PostRequest{}
	mi := &file_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostRequest) ProtoMessage() {}

func (x *PostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostRequest.ProtoReflect.Descriptor instead.
func (*PostRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *PostRequest) GetPostId() int64 {
	if x != nil {
		return x.PostId
	}
	return 0
}

// PostInfo 帖子信息（脱敏：不含正文全文等敏感内容）。
type PostInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`                                  // 帖子 ID
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`                             // 标题
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`                           // 状态（published/draft/private/...）
	AuthorId      int64                  `protobuf:"varint,4,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`      // 作者 ID
	AuthorName    string                 `protobuf:"bytes,5,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"` // 作者昵称
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInfo) Reset() {
	*x = PostInfo{}
	mi := &file_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInfo) ProtoMessage() {}

func (x *PostInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInfo.ProtoReflect.Descriptor instead.
func (*PostInfo) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *PostInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PostInfo) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PostInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PostInfo) GetAuthorId() int64 {
	if x != nil {
		return x.AuthorId
	}
	return 0
}

func (x *PostInfo) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

// SettingsSnapshot 站点设置快照（主进程仅下发白名单公开键，不含密钥类敏感键）。
type SettingsSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        map[string]string      `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // 白名单键值对
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsSnapshot) Reset() {
	*x = SettingsSnapshot{}
	mi := &file_plugin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsSnapshot) ProtoMessage() {}

func (x *SettingsSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsSnapshot.ProtoReflect.Descriptor instead.
func (*SettingsSnapshot) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{14}
}

func (x *SettingsSnapshot) GetValues() map[string]string {
	if x != nil {
		return x.Values
	}
	return nil
}

// ActivateRequest 激活请求（M3.8：许可证 + 数据服务 broker ID 一次性下发）。
type ActivateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	License       *LicenseInfo           `protobuf:"bytes,1,opt,name=license,proto3" json:"license,omitempty"`                                  // 许可证信息（M3.5）
	DataBrokerId  int64                  `protobuf:"varint,2,opt,name=data_broker_id,json=dataBrokerId,proto3" json:"data_broker_id,omitempty"` // 主进程数据服务 broker ID（0=未授权/未提供；仅声明 data.read 能力时下发）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivateRequest) Reset() {
	*x = ActivateRequest{}
	mi := &file_plugin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivateRequest) ProtoMessage() {}

func (x *ActivateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivateRequest.ProtoReflect.Descriptor instead.
func (*ActivateRequest) Descriptor() ([]byte, []int) {
	return file_plugin_proto_rawDescGZIP(), []int{15}
}

func (x *ActivateRequest) GetLicense() *LicenseInfo {
	if x != nil {
		return x.License
	}
	return nil
}

func (x *ActivateRequest) GetDataBrokerId() int64 {
	if x != nil {
		return x.DataBrokerId
	}
	return 0
}

var File_plugin_proto protoreflect.FileDescriptor

const file_plugin_proto_rawDesc = "" +
	"\n" +
	"\fplugin.proto\x12\x10yueyan.plugin.v1\"\a\n" +
	"\x05Empty\"\x8e\x02\n" +
	"\n" +
	"PluginInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12\x16\n" +
	"\x06author\x18\x04 \x01(\tR\x06author\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\x12\x14\n" +
	"\x05hooks\x18\x06 \x03(\tR\x05hooks\x12\x12\n" +
	"\x04apis\x18\a \x03(\tR\x04apis\x12:\n" +
	"\bsettings\x18\b \x03(\v2\x1e.yueyan.plugin.v1.SettingFieldR\bsettings\x12\"\n" +
	"\fcapabilities\x18\t \x03(\tR\fcapabilities\"~\n" +
	"\fSettingField\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x18\n" +
	"\adefault\x18\x04 \x01(\tR\adefault\x12\x18\n" +
	"\aoptions\x18\x05 \x03(\tR\aoptions\"\x89\x01\n" +
	"\n" +
	"ConfigInfo\x12@\n" +
	"\x06values\x18\x01 \x03(\v2(.yueyan.plugin.v1.ConfigInfo.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\x06Status\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"q\n" +
	"\vHookRequest\x12\x12\n" +
	"\x04hook\x18\x01 \x01(\tR\x04hook\x12\x19\n" +
	"\btrace_id\x18\x02 \x01(\tR\atraceId\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\x03R\aactorId\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"d\n" +
	"\fHookResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x16\n" +
	"\x06modify\x18\x03 \x01(\fR\x06modify\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"I\n" +
	"\aAPICall\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"Q\n" +
	"\rAPICallResult\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"~\n" +
	"\vLicenseInfo\x12\x18\n" +
	"\aedition\x18\x01 \x01(\tR\aedition\x12\x1a\n" +
	"\bfeatures\x18\x02 \x03(\tR\bfeatures\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x1a\n" +
	"\bdegraded\x18\x04 \x01(\bR\bdegraded\"&\n" +
	"\vUserRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"{\n" +
	"\bUserInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x10\n" +
	"\x03bio\x18\x05 \x01(\tR\x03bio\"&\n" +
	"\vPostRequest\x12\x17\n" +
	"\apost_id\x18\x01 \x01(\x03R\x06postId\"\x86\x01\n" +
	"\bPostInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x1b\n" +
	"\tauthor_id\x18\x04 \x01(\x03R\bauthorId\x12\x1f\n" +
	"\vauthor_name\x18\x05 \x01(\tR\n" +
	"authorName\"\x95\x01\n" +
	"\x10SettingsSnapshot\x12F\n" +
	"\x06values\x18\x01 \x03(\v2..yueyan.plugin.v1.SettingsSnapshot.ValuesEntryR\x06values\x1a9\n" +
	"\vValuesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"p\n" +
	"\x0fActivateRequest\x127\n" +
	"\alicense\x18\x01 \x01(\v2\x1d.yueyan.plugin.v1.LicenseInfoR\alicense\x12$\n" +
	"\x0edata_broker_id\x18\x02 \x01(\x03R\fdataBrokerId2\xe5\x01\n" +
	"\vDataService\x12D\n" +
	"\aGetUser\x12\x1d.yueyan.plugin.v1.UserRequest\x1a\x1a.yueyan.plugin.v1.UserInfo\x12D\n" +
	"\aGetPost\x12\x1d.yueyan.plugin.v1.PostRequest\x1a\x1a.yueyan.plugin.v1.PostInfo\x12J\n" +
	"\vGetSettings\x12\x17.yueyan.plugin.v1.Empty\x1a\".yueyan.plugin.v1.SettingsSnapshot2\x9d\x02\n" +
	"\rPluginService\x12=\n" +
	"\x04Info\x12\x17.yueyan.plugin.v1.Empty\x1a\x1c.yueyan.plugin.v1.PluginInfo\x12G\n" +
	"\bActivate\x12!.yueyan.plugin.v1.ActivateRequest\x1a\x18.yueyan.plugin.v1.Status\x12?\n" +
	"\n" +
	"Deactivate\x12\x17.yueyan.plugin.v1.Empty\x1a\x18.yueyan.plugin.v1.Status\x12C\n" +
	"\tSetConfig\x12\x1c.yueyan.plugin.v1.ConfigInfo\x1a\x18.yueyan.plugin.v1.Status2W\n" +
	"\vHookService\x12H\n" +
	"\aExecute\x12\x1d.yueyan.plugin.v1.HookRequest\x1a\x1e.yueyan.plugin.v1.HookResponse2O\n" +
	"\tPluginAPI\x12B\n" +
	"\x04Call\x12\x19.yueyan.plugin.v1.APICall\x1a\x1f.yueyan.plugin.v1.APICallResultB5Z3github.com/roberts9012062/boke/pkg/plugin-sdk/protob\x06proto3"

var (
	file_plugin_proto_rawDescOnce sync.Once
	file_plugin_proto_rawDescData []byte
)

func file_plugin_proto_rawDescGZIP() []byte {
	file_plugin_proto_rawDescOnce.Do(func() {
		file_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)))
	})
	return file_plugin_proto_rawDescData
}

var file_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_plugin_proto_goTypes = []any{
	(*Empty)(nil),            // 0: yueyan.plugin.v1.Empty
	(*PluginInfo)(nil),       // 1: yueyan.plugin.v1.PluginInfo
	(*SettingField)(nil),     // 2: yueyan.plugin.v1.SettingField
	(*ConfigInfo)(nil),       // 3: yueyan.plugin.v1.ConfigInfo
	(*Status)(nil),           // 4: yueyan.plugin.v1.Status
	(*HookRequest)(nil),      // 5: yueyan.plugin.v1.HookRequest
	(*HookResponse)(nil),     // 6: yueyan.plugin.v1.HookResponse
	(*APICall)(nil),          // 7: yueyan.plugin.v1.APICall
	(*APICallResult)(nil),    // 8: yueyan.plugin.v1.APICallResult
	(*LicenseInfo)(nil),      // 9: yueyan.plugin.v1.LicenseInfo
	(*UserRequest)(nil),      // 10: yueyan.plugin.v1.UserRequest
	(*UserInfo)(nil),         // 11: yueyan.plugin.v1.UserInfo
	(*PostRequest)(nil),      // 12: yueyan.plugin.v1.PostRequest
	(*PostInfo)(nil),         // 13: yueyan.plugin.v1.PostInfo
	(*SettingsSnapshot)(nil), // 14: yueyan.plugin.v1.SettingsSnapshot
	(*ActivateRequest)(nil),  // 15: yueyan.plugin.v1.ActivateRequest
	nil,                      // 16: yueyan.plugin.v1.ConfigInfo.ValuesEntry
	nil,                      // 17: yueyan.plugin.v1.SettingsSnapshot.ValuesEntry
}
var file_plugin_proto_depIdxs = []int32{
	2,  // 0: yueyan.plugin.v1.PluginInfo.settings:type_name -> yueyan.plugin.v1.SettingField
	16, // 1: yueyan.plugin.v1.ConfigInfo.values:type_name -> yueyan.plugin.v1.ConfigInfo.ValuesEntry
	17, // 2: yueyan.plugin.v1.SettingsSnapshot.values:type_name -> yueyan.plugin.v1.SettingsSnapshot.ValuesEntry
	9,  // 3: yueyan.plugin.v1.ActivateRequest.license:type_name -> yueyan.plugin.v1.LicenseInfo
	10, // 4: yueyan.plugin.v1.DataService.GetUser:input_type -> yueyan.plugin.v1.UserRequest
	12, // 5: yueyan.plugin.v1.DataService.GetPost:input_type -> yueyan.plugin.v1.PostRequest
	0,  // 6: yueyan.plugin.v1.DataService.GetSettings:input_type -> yueyan.plugin.v1.Empty
	0,  // 7: yueyan.plugin.v1.PluginService.Info:input_type -> yueyan.plugin.v1.Empty
	15, // 8: yueyan.plugin.v1.PluginService.Activate:input_type -> yueyan.plugin.v1.ActivateRequest
	0,  // 9: yueyan.plugin.v1.PluginService.Deactivate:input_type -> yueyan.plugin.v1.Empty
	3,  // 10: yueyan.plugin.v1.PluginService.SetConfig:input_type -> yueyan.plugin.v1.ConfigInfo
	5,  // 11: yueyan.plugin.v1.HookService.Execute:input_type -> yueyan.plugin.v1.HookRequest
	7,  // 12: yueyan.plugin.v1.PluginAPI.Call:input_type -> yueyan.plugin.v1.APICall
	11, // 13: yueyan.plugin.v1.DataService.GetUser:output_type -> yueyan.plugin.v1.UserInfo
	13, // 14: yueyan.plugin.v1.DataService.GetPost:output_type -> yueyan.plugin.v1.PostInfo
	14, // 15: yueyan.plugin.v1.DataService.GetSettings:output_type -> yueyan.plugin.v1.SettingsSnapshot
	1,  // 16: yueyan.plugin.v1.PluginService.Info:output_type -> yueyan.plugin.v1.PluginInfo
	4,  // 17: yueyan.plugin.v1.PluginService.Activate:output_type -> yueyan.plugin.v1.Status
	4,  // 18: yueyan.plugin.v1.PluginService.Deactivate:output_type -> yueyan.plugin.v1.Status
	4,  // 19: yueyan.plugin.v1.PluginService.SetConfig:output_type -> yueyan.plugin.v1.Status
	6,  // 20: yueyan.plugin.v1.HookService.Execute:output_type -> yueyan.plugin.v1.HookResponse
	8,  // 21: yueyan.plugin.v1.PluginAPI.Call:output_type -> yueyan.plugin.v1.APICallResult
	13, // [13:22] is the sub-list for method output_type
	4,  // [4:13] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_plugin_proto_init() }
func file_plugin_proto_init() {
	if File_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_proto_rawDesc), len(file_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_plugin_proto_goTypes,
		DependencyIndexes: file_plugin_proto_depIdxs,
		MessageInfos:      file_plugin_proto_msgTypes,
	}.Build()
	File_plugin_proto = out.File
	file_plugin_proto_goTypes = nil
	file_plugin_proto_depIdxs = nil
}
